### PR TITLE
fix: improve issue status readavility, close #24

### LINKED ISSUE #24: Decorate issue search with `[STATUS]`
Currently we format issues in suggestions like:
`#$id $status $title`
This is better:
`#$id [$status] $title`

Thank you Kristoffer

### PR DESCRIPTION
**Pull request by krfl**
Add surrounding brackets to issue status to improve readability

Screenshot 2024-03-05 at 13 17 47

### CODE REVIEW

File: src/gh/issue.rs [hunk 1]
```diff
@@ -33,7 +33,7 @@ impl GetDetail for Issue {
     fn get_detail(&self) -> String {
         let title = self.title.to_string();
         format!(
-            "{} {} {}\n{}",
+            "{} [{}] {}\n{}",
```
Comment (AlexanderBrevig) [inline src/gh/issue.rs:36]: We should make this markdown I think
```suggestion
            "# {} [{}] {}\n\n{}",
```

**Review by AlexanderBrevig — CHANGES_REQUESTED** [review]

**Review by AlexanderBrevig — APPROVED** [review]
